export const fetchConstants = {

    FETCH_LOGS_REQUEST: 'FETCH_LOGS_REQUEST',
    FETCH_LOGS_SUCCESS: 'FETCH_LOGS_SUCCESS',
    FETCH_LOGS_FAILURE: 'FETCH_LOGS_FAILURE',

    FETCH_STATISTICS_REQUEST: 'FETCH_STATISTICS_REQUEST',
    FETCH_STATISTICS_SUCCESS: 'FETCH_STATISTICS_SUCCESS',
    FETCH_STATISTICS_FAILURE: 'FETCH_STATISTICS_FAILURE'
    
};
    